branch-defaults:
  default:
    environment: ices-env
deploy:
  artifact: build/libs/ices-0.0.1-SNAPSHOT.jar
environment-defaults:
  ices-env:
    branch: null
    repository: null
global:
  application_name: ICES
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Java 8 running on
    64bit Amazon Linux/2.5.5
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
