SELECT * FROM BANK;

INSERT INTO BANK(NAME_BANK,DESC_BANK,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI, DATE_MODIFI )
VALUES ('Scotiabank', 'Bank of Nova Scotia','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK(NAME_BANK,DESC_BANK,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI, DATE_MODIFI )
VALUES ('RBC', 'Royal Bank of Canada','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK(NAME_BANK,DESC_BANK,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI, DATE_MODIFI )
VALUES ('TD Canada Trust', 'Toronto-Dominion Bank','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK(NAME_BANK,DESC_BANK,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI, DATE_MODIFI )
VALUES ('BMO Financial Group', 'Bank of Montreal','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK(NAME_BANK,DESC_BANK,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI, DATE_MODIFI )
VALUES ('HSBC', 'HSBC Bank Canada','A','SYSTEM',sysdate(),'SYSTEM',sysdate());