ALTER TABLE BANK_ACCOUNT AUTO_INCREMENT = 1

SELECT * FROM BANK_ACCOUNT;
SELECT * FROM MASTER_BANK_ACCOUNT;

INSERT INTO BANK_ACCOUNT(ID_BANK,ID_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,ID_COSTUMER,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES(3,2,102,4,6641598,1,'A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK_ACCOUNT(ID_BANK,ID_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,ID_COSTUMER,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES(1,3,103,5,2554496,1,'A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK_ACCOUNT(ID_BANK,ID_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,ID_COSTUMER,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES(2,1,104,6,1417535,1,'A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO BANK_ACCOUNT(ID_BANK,ID_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,ID_COSTUMER,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES(4,4,105,7,3756455,1,'A','SYSTEM',sysdate(),'SYSTEM',sysdate());


DELETE FROM BANK_ACCOUNT WHERE CODE_BANK_TRANSIT NOT IN (SELECT CODE_BANK_TRANSIT FROM MASTER_BANK_ACCOUNT);
DELETE FROM BANK_ACCOUNT WHERE CODE_INSTITUTION NOT IN (SELECT CODE_INSTITUTION FROM MASTER_BANK_ACCOUNT);
DELETE FROM BANK_ACCOUNT WHERE NUMB_ACCOUNT NOT IN (SELECT NUMB_ACCOUNT FROM MASTER_BANK_ACCOUNT);
