
SELECT * FROM CURRENCY;

INSERT INTO CURRENCY(NAME_CURRENCY,NAME_SYMBOL,CODE_CURRENCY,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES ('Euro','€','EUR','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO CURRENCY(NAME_CURRENCY,NAME_SYMBOL,CODE_CURRENCY,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES ('American Dollar','$','USD','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO CURRENCY(NAME_CURRENCY,NAME_SYMBOL,CODE_CURRENCY,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES ('Canadian Dollar','$','CAN','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO CURRENCY(NAME_CURRENCY,NAME_SYMBOL,CODE_CURRENCY,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES ('Yuan','¥','CNY','A','SYSTEM',sysdate(),'SYSTEM',sysdate());