
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER(NAME_FIRST,NAME_MIDDLE,NAME_LAST,DATE_BIRTH,NAME_ADDRESS,CODE_POSTAL,NAME_CITY,CODE_PROVINCE,CODE_COUNTRY,TYPE_PHONE,NUMB_PHONE,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES ('CARLOS','G','ZEGARRA',sysdate(),'1600 Univerity Avenue','N9B 4Y5','Windsor','ON','CA','CELL','647-888-1234', 'A', 'SYSTEM', sysdate(), 'SYSTEM', sysdate());