INSERT INTO MASTER_BANK(NAME_BANK,DESC_BANK,STATUS)
VALUES ('Scotiabank', 'Bank of Nova Scotia','A');
INSERT INTO MASTER_BANK(NAME_BANK,DESC_BANK,STATUS)
VALUES ('RBC', 'Royal Bank of Canada','A');
INSERT INTO MASTER_BANK(NAME_BANK,DESC_BANK,STATUS)
VALUES ('TD Canada Trust', 'Toronto-Dominion Bank','A');
INSERT INTO MASTER_BANK(NAME_BANK,DESC_BANK,STATUS)
VALUES ('BMO Financial Group', 'Bank of Montreal','A');
INSERT INTO MASTER_BANK(NAME_BANK,DESC_BANK,STATUS)
VALUES ('HSBC', 'HSBC Bank Canada','A');