INSERT INTO MASTER_CURRENCY(NAME_CURRENCY,STATUS)
VALUES ('Euro','A');
INSERT INTO MASTER_CURRENCY(NAME_CURRENCY,STATUS)
VALUES ('American Dollar','A');
INSERT INTO MASTER_CURRENCY(NAME_CURRENCY,STATUS)
VALUES ('Canadian Dollar','A');
INSERT INTO MASTER_CURRENCY(NAME_CURRENCY,STATUS)
VALUES ('Yuan','A');