ALTER TABLE MASTER_BANK_ACCOUNT AUTO_INCREMENT = 1

SELECT * FROM MASTER_BANK_ACCOUNT;

INSERT INTO MASTER_BANK_ACCOUNT(ID_MASTER_BANK,ID_MASTER_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,NUMB_ACCOUNT_BALANCE,PASSWORD,STATUS)
VALUES(3,2,102,4,6641598,30000,'$2a$10$p0PC4zjCQjBozGvbyX8xZ.RNggUJ.St3lu4FtkRL/jJ6IqZNqaQKK','A');
INSERT INTO MASTER_BANK_ACCOUNT(ID_MASTER_BANK,ID_MASTER_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,NUMB_ACCOUNT_BALANCE,PASSWORD,STATUS)
VALUES(1,3,103,5,2554496,50000,'$2a$10$p0PC4zjCQjBozGvbyX8xZ.RNggUJ.St3lu4FtkRL/jJ6IqZNqaQKK','A');
INSERT INTO MASTER_BANK_ACCOUNT(ID_MASTER_BANK,ID_MASTER_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,NUMB_ACCOUNT_BALANCE,PASSWORD,STATUS)
VALUES(2,1,104,6,1417535,40000,'$2a$10$p0PC4zjCQjBozGvbyX8xZ.RNggUJ.St3lu4FtkRL/jJ6IqZNqaQKK','A');
INSERT INTO MASTER_BANK_ACCOUNT(ID_MASTER_BANK,ID_MASTER_CURRENCY,CODE_BANK_TRANSIT,CODE_INSTITUTION,NUMB_ACCOUNT,NUMB_ACCOUNT_BALANCE,PASSWORD,STATUS)
VALUES(4,4,105,7,3756455,60000,'$2a$10$p0PC4zjCQjBozGvbyX8xZ.RNggUJ.St3lu4FtkRL/jJ6IqZNqaQKK','A');




