INSERT INTO role(NAME_ROLE,DESC_ROLE,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES('ROLE_ADMIN','Admin','A','SYSTEM',sysdate(),'SYSTEM',sysdate());
INSERT INTO role(NAME_ROLE,DESC_ROLE,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES('ROLE_USER','User','A','SYSTEM',sysdate(),'SYSTEM',sysdate());