INSERT USER(EMAIL,PASSWORD,ID_CUSTOMER,STATUS,USER_REGIST,DATE_REGIST,USER_MODIFI,DATE_MODIFI)
VALUES('admin','$2a$10$p0PC4zjCQjBozGvbyX8xZ.RNggUJ.St3lu4FtkRL/jJ6IqZNqaQKK',1,'A','SYSTEM',sysdate(),'SYSTEM',sysdate());
