spring:
  profiles:
    active: local
  mvc:
    favicon:
      enabled: true

################################################################################
# ALL ENVIRONMENTS #############################################################
################################################################################

# Server

#server:
#  contextPath: /ssge-negocio
  
# Banner

banner:
  charset: UTF-8
  location: classpath:/banner/ices.txt

---
################################################################################
# LOCAL ENVIRONMENT ############################################################
################################################################################

# Database Settings
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://icesdb.uwindsor-ices.ca:3306/icesdb?autoReconnect=true&useSSL=false
    username: admin
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
    initialize: false
    continue-on-error: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# Server

server:
  port: 8080
  session:
    timeout: 900

# Logger

logging:
  level:
    ca.uwindsor.ices: DEBUG
    org.hibernate.type: INFO
 
# Security
     
# Parameters 


---
################################################################################
# DEVELOPMENT ENVIRONMENT ######################################################
################################################################################

# Database Settings

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
    initialize: false
    continue-on-error: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# Server

server:
  port: 5000
  session:
    timeout: 300 
    
# Logger

logging:
  level:
    ca.uwindsor.ices: DEBUG
    org.hibernate.type: INFO

# Security

# Parameters

---
################################################################################
# PRODUCTION ENVIRONMENT #######################################################
################################################################################

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 5
      test-on-borrow: true
    initialize: false
    continue-on-error: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

# Server

server:
  port: 5000
  session:
    timeout: 300 
    
# Logger

logging:
  level:
    ca.uwindsor.ices: DEBUG
    org.hibernate.type: INFO

# Security

     
# Parameters
